### ISSUE TITLE
Latest version not available in Maven Central

### ISSUE THREAD

**Issue by ghost** [tklein/gradle-jaxws-plugin#8]
The plugin that is available in Maven Central I guess does not have the latest changes for Gradle 2.0 compatibility. Below error is thrown when plugin is used with Gradle 2+

```
> Failed to apply plugin [id 'jaxws']
   > Could not find method add() for arguments [jaxws, eu.schnuckelig.gradle.plugins.jaxws.JaxWSPlugin$_apply_closure1@60e4b368] on configuration container.
```

**Comment by tklein** [comment]
Uploaded the latest version to Sonatype repo (https://oss.sonatype.org/content/repositories/releases/eu/schnuckelig/gradle/gradle-jaxws-plugin/) which shall be synced to Maven central in a couple of minutes
